---
- hosts: all
  become: yes

  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/set_host.yml
      tags:
        - always
        - host
    - import_tasks: tasks/ssh_port.yml
      tags:
        - always
        - port
    - import_tasks: tasks/bootstrap.yml
      tags:
        - bootstrap

  roles:
    - role: system
      tags:
        - system
    
    - role: filesystems
      tags:
        - filesystems
      when: external_disk

    - role: backup
      tags:
        - backup
      when: backup_disk

    - role: networking/connection
      tags:
        - connection
      when: enable_connection

    - role: firewall
      tags:
        - firewall

    - role: networking/ddclient
      tags:
        - ddclient
      when: enable_ddclient

    - role: networking/nameserver
      tags:
        - nameserver
      when: '"nameserver" in group_names'

    - role: networking/hosts
      tags:
        - hosts

    - role: mail
      tags:
        - mail
      when: '"mailserver" in group_names'

    - role: caddy
      tags:
        - caddy
      when: '"caddy" in group_names'

    - role: haproxy
      tags:
        - haproxy
      when: '"haproxy" in group_names'

    - role: wireguard
      tags:
        - wireguard
      when: '"wireguard" in group_names'

    - role: synapse
      tags:
        - synapse
      when: '"synapse" in group_names'

    - role: containers
      tags:
        - containers
      when: '"fleet" in group_names'

    - role: syncthing
      tags:
        - syncthing
      when: '"syncthing" in group_names'

    - role: website
      tags:
        - website
      when: '"website" in group_names'

    - role: dotfiles
      tags:
        - dotfiles
      when: enable_dotfiles
      dotfile_users:
        - "{{ ansible_user }}"
        - "{{ username }}"
