- name: Determine if host is up at static IP
  local_action: "command ping -c 1 {{ local_ip }}"
  become: no
  ignore_errors: true
  changed_when: false
  register: up_static

- name: Switch ansible_host to fallback
  set_fact:
    ansible_host: "{{ fallback_host }}"
  when: up_static.rc != 0 

- name: Switch ansible_host to static IP
  set_fact:
    ansible_host: "{{ local_ip }}"
  when: up_static.rc == 0
