---

- name: Install dotfile manager
  community.general.pacman:
    name:
      - chezmoi

- name: Init dotfiles
  shell:
    cmd: "umask 007; chezmoi init {{ dots_repo }} --force --depth 1 --promptDefaults"
  become: true
  become_user: "{{ item }}"
  with_items: "{{ dotfile_users }}"

- name: Update dotfiles
  shell:
    cmd: "umask 007; chezmoi update --force"
  become: true
  become_user: "{{ item }}"
  with_items: "{{ dotfile_users }}"
