---
# override these in host_vars

# static IP interface
net_interface: eth0
# e.g. wifi
conn_type: ethernet
# if you have a wireless connection already, set this to its name to use it
conn_name: wired
# wifi connection name
conn_ssid: ""
# set this in the secret template
conn_pass: ""

# LAN static IP address
local_ip: null
subnet_prefix: /24
local_subnet: 192.168.0.0/24
# router IP address
gateway: 192.168.0.1

# Can be the server itself if it has a nameserver
nameserver: "{{ hostvars[groups['nameserver'][0]]['local_ip'] }}"
