---

# password for ddclient
ddclient_pass: ""

# syncthing gui password
syncthing_gui_pass: ""

# Matrix Synapse secrets
# You can generate these with:
#
#   docker run -it --rm \
#    --mount type=volume,src=synapse-data,dst=/data \
#    -e SYNAPSE_SERVER_NAME=my.matrix.host \
#    -e SYNAPSE_REPORT_STATS=yes \
#    matrixdotorg/synapse:latest generate
#
# Just yoink the secrets out of the configuration file it makes
# Otherwise cat /dev/urandom | base64 | head -c 32 probably works too
registration_shared_secret: ""
macaroon_secret_key: ""
form_secret: ""

# paperless secret key
paperless_secret: ""
