---
# these are defaults
# change these in group/host vars

# NOTE: copy the *entire* wireguard config if you wish to override it (all or nothing)

# also see group_vars/all/00-secret-template.yml

wireguard:
  dns_servers:
    - "{{ dns_forward }}"
  interface: "wg0"
  ip:
    # address for the server
    address: "10.66.77.1/32"
    # cidr range in tunnel
    cidr: "10.66.77.0/24"

    server_public: "www.{{ domain }}"
    # UDP port
    port: 51820

  # place to output client configs
  client_folder: "/tmp/wireguard-clients"
